stages:
 - generate
 - deploy

.fedora.latest.template: &fedora_template
  image: fedora:44
  tags:
  - saas-linux-small-amd64
  before_script:
#in F34 rubygem-ronn got replaced by rubygem-ronn-ng
    - dnf install -y libmaxminddb-devel make meson ninja-build gcc libasan libubsan geolite2-{city,country} rubygem-ronn jq perl-interpreter perl-bignum

fedora.nogeo:
  stage: generate
  <<: *fedora_template
  script:
    - meson setup build -Duse_maxminddb=disabled -Duse_geoip=enabled --buildtype=plain -Dc_args="-O2 -g -Werror"
    - ninja -C build
    - ninja -C build test
    - USE_MAXMIND=no USE_RUNTIME_LINKING=no CFLAGS="-O2 -g -Werror" make

fedora.maxmind:
  stage: generate
  <<: *fedora_template
  script:
    - meson setup build -Duse_maxminddb=enabled -Duse_runtime_linking=disabled --buildtype=plain -Dc_args="-O2 -g -Werror"
    - ninja -C build
    - ninja -C build test
    - USE_RUNTIME_LINKING=no USE_MAXMIND=yes CFLAGS="-O2 -g -Werror" make

fedora.dyn_maxmind:
  stage: generate
  <<: *fedora_template
  script:
    - meson setup build -Duse_maxminddb=enabled -Duse_runtime_linking=enabled --buildtype=plain -Dc_args="-O2 -g -Werror"
    - ninja -C build
    - ninja -C build test
    - USE_RUNTIME_LINKING=yes USE_MAXMIND=yes CFLAGS="-O2 -g -Werror" make

fedora.sanitizers:
  stage: generate
  <<: *fedora_template
  script:
    - export ASAN_OPTIONS="detect_leaks=0"
    - export UBSAN_OPTIONS="print_stacktrace=1"
    - meson setup build -Duse_maxminddb=enabled -Duse_runtime_linking=enabled -Db_sanitize=address,undefined -Dc_args="-fno-sanitize-recover=undefined" -Dwerror=true
    - ninja -C build test
    - ./build/ipcalc -g 217.31.205.50

# Generates coverage report
pages-test:
  stage: deploy
  <<: *fedora_template
  script:
    - dnf install -y lcov
    - meson setup build -Db_coverage=true -Duse_maxminddb=enabled -Duse_runtime_linking=enabled --buildtype=plain -Dc_args="-Og -g -Werror"
    - ninja -C build
    - ninja -C build test
    - ninja -C build coverage-html
    - mv build/meson-logs/coveragereport public
    - tests/run-coverage.sh
  except:
    - master

pages:
  stage: deploy
  <<: *fedora_template
  script:
    - dnf install -y lcov
    - meson setup build -Db_coverage=true -Duse_maxminddb=enabled -Duse_runtime_linking=enabled --buildtype=plain -Dc_args="-Og -g -Werror"
    - ninja -C build
    - ninja -C build test
    - ninja -C build coverage-html
    - mv build/meson-logs/coveragereport public
    - tests/run-coverage.sh
  coverage: '/coverage lines: \d+\.\d+/'
  artifacts:
    when: on_success
    paths:
    - public
  only:
    - master
