option('use_geoip',
	type : 'feature',
	value : 'auto',
	description : 'Ignored; libGeoIP is no longer supported'
)
option('use_maxminddb',
	type : 'feature',
	value : 'auto',
	description : 'Use the maxminddb library to retrieve geo-information'
)
option('use_runtime_linking',
	type : 'feature',
	value : 'auto',
	description : 'Load the maxminddb library at runtime if available'
)
